import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import EmotionRegistry from './_modules/common/EmotionRegistry';
import { Provider } from 'jotai';
import { ReactQueryProvider } from './config/ReactQueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <EmotionRegistry>
          <ReactQueryProvider>
            <Provider>
              <p>From Layout</p>
              {children}
            </Provider>
          </ReactQueryProvider>
        </EmotionRegistry>
      </body>
    </html>
  );
}
